apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: devopsexamplenew123456
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: devopsexamplenew123456
  template:
    metadata:
      labels:
        app: devopsexamplenew123456
    spec:
      containers:
      - name: react-app #The name of the react.js application container
        image: devopsexamplenew123456:latest #The Docker image for building the React.js application container
        ports:
        - containerPort: 3000 #The port for the React.js application   container
